[phases.setup]
packages = ["ffmpeg", "git", "bash", "curl", "build-essential", "libffi-dev", "libssl-dev", "python3-dev"]

[phases.install]
commands = [
  "mkdir -p /app",
  "git clone --depth=1 https://github.com/TeamUltroid/Ultroid.git /app",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r /app/requirements.txt",
  "pip install -r /app/resources/startup/optional-requirements.txt",
  "pip install telethon gitpython python-decouple python-dotenv telegraph enhancer requests aiohttp catbox-uploader cloudscraper"
]

[phases.start]
commands = [
  "mkdir -p /data/Ultroid",
  "cp -rn /app/. /data/Ultroid/",
  "cd /data/Ultroid",
  "export SESSION=/data/Ultroid/pyUltroid.session",
  "while true; do python3 -m pyUltroid || true; echo 'Bot exited, restarting in 10s...'; sleep 10; done"
]
